# =============================================================================
# TestMart - Authentication & Authorization Feature Suite
# Generated by: Principal SDET / BDD Specialist
# Coverage: Auth flows, RBAC, security, edge cases
# Roles: Super Admin | Merchant | Customer
# =============================================================================

# =============================================================================
# FEATURE 1: USER AUTHENTICATION
# =============================================================================

Feature: User Authentication
  As a registered TestMart user
  I want to securely authenticate into the application
  So that I can access role-appropriate features

  Background:
    Given the TestMart application is running
    And the authentication service is available
    And no user is currently authenticated

  # ---------------------------------------------------------------------------
  # HAPPY PATH
  # ---------------------------------------------------------------------------

  @smoke @regression @authentication
  Scenario Outline: Successful login for each user role
    Given a registered user exists with role "<role>"
    When the user authenticates with valid credentials for role "<role>"
    Then the user should be granted access
    And a short-lived access token should be issued
    And a long-lived refresh token should be issued
    And the user should be directed to the "<dashboard>" dashboard

    Examples:
      | role        | dashboard        |
      | Super Admin | admin            |
      | Merchant    | merchant         |
      | Customer    | customer         |

  @smoke @regression @authentication
  Scenario: Access token is used for authenticated requests
    Given a registered Customer has successfully authenticated
    When the customer makes a request to a protected endpoint
    Then the request should include the access token
    And the backend middleware should validate the token
    And the response should be returned successfully

  @regression @authentication
  Scenario: Refresh token extends the user session
    Given a registered Merchant has an expired access token
    And the Merchant holds a valid refresh token
    When the session refresh is triggered
    Then a new short-lived access token should be issued
    And the Merchant should remain authenticated without re-entering credentials

  @regression @authentication
  Scenario: User can log out successfully
    Given a Super Admin is currently authenticated
    When the Super Admin initiates a logout
    Then the session should be terminated
    And the access token should be invalidated
    And the user should be redirected to the login page

  # ---------------------------------------------------------------------------
  # NEGATIVE SCENARIOS
  # ---------------------------------------------------------------------------

  @regression @negative @authentication
  Scenario Outline: Login fails with invalid credentials
    Given a registered user exists with role "Customer"
    When the user attempts to authenticate with "<email>" and "<password>"
    Then authentication should be denied
    And an appropriate error message should be displayed
    And no tokens should be issued

    Examples:
      | email                      | password         | scenario                 |
      | valid@example.com          | wrongpassword    | incorrect password       |
      | nonexistent@example.com    | anyPassword1!    | unregistered email       |
      | valid@example.com          |                  | blank password           |
      |                            | anyPassword1!    | blank email              |
      |                            |                  | both fields empty        |
      | not-an-email               | anyPassword1!    | malformed email format   |

  @regression @negative @authentication
  Scenario: Login fails when account does not exist in the database
    When an unauthenticated user attempts to authenticate with a non-registered email
    Then authentication should be denied
    And the system should not reveal whether the email is registered

  @regression @negative @authentication
  Scenario: Expired access token is rejected by backend middleware
    Given a registered Customer has an expired access token
    And no valid refresh token is available
    When the customer attempts to access a protected resource
    Then the request should be rejected with an unauthorized error
    And the user should be prompted to re-authenticate

  @regression @negative @authentication
  Scenario: Tampered JWT token is rejected
    Given a registered Merchant has a valid access token
    When the token payload is modified externally
    And the Merchant attempts to access a protected endpoint with the tampered token
    Then the request should be rejected
    And an unauthorized error should be returned

  # ---------------------------------------------------------------------------
  # SECURITY SCENARIOS
  # ---------------------------------------------------------------------------

  @security @regression @authentication
  Scenario: Account is locked after repeated failed login attempts
    Given a registered Customer account exists
    When the user fails authentication 3 consecutive times with incorrect credentials
    Then the account should be locked
    And further login attempts should be denied for 5 minutes
    And an account lockout notification should be displayed

  @security @regression @authentication
  Scenario: Locked account cannot authenticate even with correct credentials
    Given a Customer account is currently locked due to failed attempts
    When the user attempts to authenticate with correct credentials
    Then authentication should be denied
    And a lockout message should be shown with remaining lock duration

  @security @regression @authentication
  Scenario: Account lock expires after the cooldown period
    Given a Customer account was locked 5 minutes ago
    When the user attempts to authenticate with correct credentials
    Then authentication should succeed
    And a new session should be established

  @security @regression @authentication
  Scenario: Brute-force attack is throttled by rate limiting
    Given a login endpoint is targeted with rapid successive requests
    When more than the allowed request threshold is exceeded within a short window
    Then subsequent requests should be rate-limited
    And the system should return an appropriate rate-limit error response

  @security @regression @authentication
  Scenario: HTTP security headers are present on authentication responses
    When a request is made to the login endpoint
    Then the response should include security headers enforced by Helmet
    And the response should include XSS protection headers

  @security @regression @authentication
  Scenario: NoSQL injection payload is rejected during authentication
    When a user attempts to authenticate using a NoSQL injection string in the email field
    Then the input should be sanitized
    And authentication should be denied
    And no database manipulation should occur

  @security @regression @authentication
  Scenario: XSS payload in login fields is neutralized
    When a user submits a script injection string as the password field value
    Then the payload should be stripped or escaped
    And the application should not execute the injected script

  @security @regression @authentication
  Scenario: Passwords are stored as bcrypt hashes
    Given a new user registers with a plaintext password
    When the stored credential is retrieved from the database
    Then the stored value should be a bcrypt hash
    And the plaintext password should not be recoverable in storage

  # ---------------------------------------------------------------------------
  # EDGE CASES
  # ---------------------------------------------------------------------------

  @regression @edge-case @authentication
  Scenario: Concurrent logins from the same account on multiple sessions
    Given a registered Merchant is authenticated in one session
    When the same account authenticates from a second session simultaneously
    Then both sessions should receive valid tokens
    And each session should function independently

  @regression @edge-case @authentication
  Scenario: Login attempt immediately after account lockout expires (boundary)
    Given a Customer account lock expires at exactly the 5-minute mark
    When the user authenticates at the precise expiry boundary with correct credentials
    Then authentication should succeed
    And a new session should be created

  @regression @edge-case @authentication
  Scenario: Accessing a protected route without any authentication token
    Given no authentication token is present in the request
    When a user navigates directly to a protected route URL
    Then access should be denied
    And the user should be redirected to the login page

  @regression @edge-case @authentication
  Scenario: Refresh token is not accepted as an access token
    Given a registered Customer holds a valid refresh token
    When the customer attempts to use the refresh token to access a protected resource
    Then the request should be rejected as unauthorized


# =============================================================================
# FEATURE 2: ROLE-BASED ACCESS CONTROL (RBAC)
# =============================================================================

Feature: Role-Based Access Control
  As the TestMart platform
  I want to enforce role-specific access to features and routes
  So that users can only perform actions permitted for their role

  Background:
    Given the TestMart application is running
    And the RBAC middleware is active on all protected routes

  # ---------------------------------------------------------------------------
  # HAPPY PATH – ROLE ACCESS
  # ---------------------------------------------------------------------------

  @smoke @regression @rbac
  Scenario Outline: Each role is granted access to their permitted routes
    Given a user is authenticated with role "<role>"
    When the user navigates to "<permitted_route>"
    Then the route should be accessible
    And the "<expected_view>" should be displayed

    Examples:
      | role        | permitted_route      | expected_view             |
      | Super Admin | /admin/users         | User management list      |
      | Super Admin | /admin/products      | All products list         |
      | Merchant    | /merchant/dashboard  | Merchant dashboard        |
      | Merchant    | /merchant/products   | Product management view   |
      | Customer    | /products            | Product browsing view     |

  @smoke @regression @rbac
  Scenario: Super Admin can view all registered users
    Given a Super Admin is authenticated
    When the Super Admin navigates to the user management section
    Then a list of all registered users should be displayed
    And individual user detail pages should be accessible

  @smoke @regression @rbac
  Scenario: Merchant dashboard displays store metrics
    Given a Merchant is authenticated
    When the Merchant views their dashboard
    Then total product count should be visible
    And top performing products should be listed
    And basic store metrics should be displayed

  @smoke @regression @rbac
  Scenario: Customer can view available products and cart icon
    Given a Customer is authenticated
    When the Customer views the product listing page
    Then all available products should be displayed
    And the Cart icon should be visible in the navigation

  @smoke @regression @rbac
  Scenario: Merchant can see the Add Product button
    Given a Merchant is authenticated
    When the Merchant views the product listing page
    Then the Add Product button should be visible

  @smoke @regression @rbac
  Scenario: Super Admin can see the Add Product button in product oversight
    Given a Super Admin is authenticated
    When the Super Admin views the product listing page
    Then the Add Product button should be visible

  # ---------------------------------------------------------------------------
  # NEGATIVE – UNAUTHORIZED ACCESS ATTEMPTS
  # ---------------------------------------------------------------------------

  @regression @negative @rbac
  Scenario Outline: Users cannot access routes outside their role permissions
    Given a user is authenticated with role "<role>"
    When the user attempts to navigate to "<restricted_route>"
    Then access should be denied
    And the user should be redirected away from the restricted route

    Examples:
      | role     | restricted_route        | reason                              |
      | Customer | /admin/users            | Admin-only route                    |
      | Customer | /merchant/dashboard     | Merchant-only route                 |
      | Customer | /merchant/products      | Merchant-only route                 |
      | Merchant | /admin/users            | Admin-only route                    |

  @regression @negative @rbac
  Scenario: Unauthenticated user is redirected from any protected route
    Given no user is authenticated
    When an unauthenticated visitor navigates to a protected route
    Then the visitor should be redirected to the login page
    And no protected content should be rendered

  @regression @negative @rbac @security
  Scenario: Customer cannot invoke Merchant product management actions via API
    Given a Customer is authenticated
    When the customer sends a direct API request to create a new product
    Then the backend RBAC middleware should reject the request
    And a forbidden error response should be returned
    And no product should be created in the database

  @regression @negative @rbac @security
  Scenario: Merchant cannot access Super Admin user management via API
    Given a Merchant is authenticated
    When the Merchant sends a direct API request to retrieve the full user list
    Then the backend RBAC middleware should reject the request
    And a forbidden error response should be returned

  # ---------------------------------------------------------------------------
  # ROLE BADGE & NAVIGATION UI
  # ---------------------------------------------------------------------------

  @regression @rbac @ui
  Scenario Outline: Navigation bar reflects the authenticated user's role
    Given a user is authenticated with role "<role>"
    When the user views the navigation bar
    Then the role badge should display "<role>"
    And navigation options should correspond to "<role>" permissions only

    Examples:
      | role        |
      | Super Admin |
      | Merchant    |
      | Customer    |

  # ---------------------------------------------------------------------------
  # EDGE CASES
  # ---------------------------------------------------------------------------

  @regression @edge-case @rbac @security
  Scenario: Role claim in JWT cannot be elevated by the client
    Given a Customer is authenticated with a valid JWT containing role "Customer"
    When the customer modifies the JWT payload to claim role "Super Admin"
    And sends a request to an admin-only endpoint with the modified token
    Then the backend should detect the token tampering
    And the request should be rejected as unauthorized

  @regression @edge-case @rbac
  Scenario: Authenticated user with an unrecognized role is denied all access
    Given a token is issued containing an undefined role value
    When the token holder attempts to access any protected route
    Then all route access should be denied
    And the user should be redirected to the login page

  @regression @edge-case @rbac
  Scenario: Session role is consistent across all requests within a session
    Given a Merchant has an active authenticated session
    When the Merchant makes multiple requests to different permitted routes
    Then each request should be authorized with the Merchant role
    And no privilege escalation should occur between requests
