[pytest]
markers =
    p0: custom mark for p0 tests
    p1: custom mark for p1 tests
    p2: custom mark for p2 tests
    smoke: custom mark for smoke tests
    regression: custom mark for regression tests
    auth: custom mark for auth tests
    security: custom mark for security tests
    rbac: custom mark for rbac tests
    jwt: custom mark for jwt tests
