"""
conftest.py — shared fixtures for the TestMart API test suite.
Auto-generated by setup_test_infra.py — safe to extend, do not delete fixtures.
"""
from __future__ import annotations

import pytest
import requests

BASE_URL = "http://localhost:5001"

LOGIN_ENDPOINT  = "/api/auth/login"
LOGOUT_ENDPOINT = "/api/auth/logout"

TEST_USERS = {
    "superadmin": {"email": "superadmin@test.com", "password": "Str0ng!Pass#2024", "role": "superadmin"},
    "merchant":   {"email": "merchant@test.com",   "password": "MerchantPass123!", "role": "merchant"},
    "customer":   {"email": "customer@test.com",   "password": "CustomerPass123!", "role": "customer"},
    "blocked_user":    {"email": "blocked@test.com",    "password": "BlockedPass123!",  "role": "customer"},
}

# ── Helpers ──────────────────────────────────────────────────

def _fetch_user_auth(role: str) -> dict:
    """Logs in and returns the full JSON response (tokens + user info) from the Auth API."""
    user = TEST_USERS[role]
    resp = requests.post(
        f"{BASE_URL}{LOGIN_ENDPOINT}",
        json={"email": user["email"], "password": user["password"]},
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()

def _get_token(role: str) -> str:
    """Helper to extract just the accessToken for a given role."""
    auth_data = _fetch_user_auth(role)
    return auth_data.get("accessToken", "")

# ── Fixtures ─────────────────────────────────────────────────

@pytest.fixture(scope="session")
def base_url() -> str:
    """The base URL for the API under test."""
    return BASE_URL

@pytest.fixture(scope="session")
def test_users_data():
    """Provides access to the static test user credentials dictionary."""
    return TEST_USERS

@pytest.fixture(scope="session")
def requests_session():
    """Shared requests.Session for the entire test session."""
    session = requests.Session()
    yield session
    session.close()

@pytest.fixture(scope="session")
def auth_tokens() -> dict:
    """
    Provides the full raw auth response for Super Admin.
    Used for tests requiring refreshTokens or raw dictionary access.
    """
    return _fetch_user_auth('superadmin')

@pytest.fixture(scope="session")
def auth_headers() -> dict:
    """Bearer token headers for the Super Admin role (P0/P1 standard)."""
    return {"Authorization": f"Bearer {_get_token('superadmin')}"}

@pytest.fixture(scope="session")
def merchant_headers() -> dict:
    """Bearer token headers for the Merchant role."""
    return {"Authorization": f"Bearer {_get_token('merchant')}"}

@pytest.fixture(scope="session")
def customer_headers() -> dict:
    """Bearer token headers for the Customer role."""
    return {"Authorization": f"Bearer {_get_token('customer')}"}