"""
conftest.py — shared fixtures for the TestMart API test suite.
Auto-generated by setup_test_infra.py — safe to extend, do not delete fixtures.
"""
from __future__ import annotations

import pytest
import requests

BASE_URL = "http://localhost:5001"

LOGIN_ENDPOINT  = "/api/auth/login"
LOGOUT_ENDPOINT = "/api/auth/logout"

TEST_USERS = {
    "superadmin": {"email": "superadmin@test.com", "password": "Str0ng!Pass#2024", "role": "superadmin"},
    "merchant":   {"email": "merchant@test.com",   "password": "MerchantPass123!", "role": "merchant"},
    "customer":   {"email": "customer@test.com",   "password": "CustomerPass123!", "role": "customer"},
    "blocked":    {"email": "blocked@test.com",    "password": "BlockedPass123!",  "role": "customer"},
}


def _get_token(role: str) -> str:
    """Login and return the accessToken for the given role."""
    user = TEST_USERS[role]
    resp = requests.post(
        f"{BASE_URL}{LOGIN_ENDPOINT}",
        json={"email": user["email"], "password": user["password"]},
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json().get("accessToken", "")


@pytest.fixture(scope="session")
def base_url() -> str:
    return BASE_URL


@pytest.fixture(scope="session")
def requests_session():
    """Shared requests.Session for the entire test session."""
    session = requests.Session()
    yield session
    session.close()


@pytest.fixture(scope="session")
def auth_headers() -> dict:
    """Bearer token headers for the Super Admin role."""
    return {"Authorization": f"Bearer {_get_token('superadmin')}"}


@pytest.fixture(scope="session")
def merchant_headers() -> dict:
    """Bearer token headers for the Merchant role."""
    return {"Authorization": f"Bearer {_get_token('merchant')}"}


@pytest.fixture(scope="session")
def customer_headers() -> dict:
    """Bearer token headers for the Customer role."""
    return {"Authorization": f"Bearer {_get_token('customer')}"}
