"""
setup_test_infra.py

Generates conftest.py and registers marks in pytest.ini.
Safe to re-run — skips files that already exist unless --force is passed.

Usage:
    python3 scripts/setup_test_infra.py --spec requirements/openapi.json --tests-dir tests
"""
from __future__ import annotations

import argparse
import json
import os
import re
from typing import List


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_spec(spec_path: str) -> dict:
    with open(spec_path, "r") as f:
        return json.load(f)


def extract_endpoints(spec: dict) -> List[dict]:
    """Pull endpoint + method + auth requirement from the spec."""
    endpoints = []
    for path, methods in spec.get("paths", {}).items():
        for method, details in methods.items():
            security = details.get("security", [])
            endpoints.append({
                "path": path,
                "method": method.upper(),
                "requires_auth": len(security) > 0,
            })
    return endpoints


def extract_marks(spec: dict) -> List[str]:
    """Derive custom marks from spec tags."""
    base_marks = ["p0", "p1", "p2", "smoke", "regression", "auth", "security", "rbac", "jwt"]
    tag_marks  = [t["name"].lower() for t in spec.get("tags", [])]
    all_marks  = list(dict.fromkeys(base_marks + tag_marks))
    return all_marks


def extract_base_url(spec: dict) -> str:
    servers = spec.get("servers", [])
    if servers:
        return servers[0].get("url", "http://localhost:5001")
    return "http://localhost:5001"


# ── Writers ───────────────────────────────────────────────────────────────────

def write_conftest(tests_dir: str, base_url: str, force: bool) -> str:
    path = os.path.join(tests_dir, "conftest.py")

    if os.path.exists(path) and not force:
        print("  [skip] conftest.py already exists (use --force to overwrite)")
        return path

    content = '''"""
conftest.py — shared fixtures for the TestMart API test suite.
Auto-generated by setup_test_infra.py — safe to extend, do not delete fixtures.
"""
from __future__ import annotations

import pytest
import requests

BASE_URL = "{base_url}"

LOGIN_ENDPOINT  = "/api/auth/login"
LOGOUT_ENDPOINT = "/api/auth/logout"

TEST_USERS = {{
    "superadmin": {{"email": "superadmin@test.com", "password": "Str0ng!Pass#2024", "role": "superadmin"}},
    "merchant":   {{"email": "merchant@test.com",   "password": "MerchantPass123!", "role": "merchant"}},
    "customer":   {{"email": "customer@test.com",   "password": "CustomerPass123!", "role": "customer"}},
    "blocked":    {{"email": "blocked@test.com",    "password": "BlockedPass123!",  "role": "customer"}},
}}


def _get_token(role: str) -> str:
    """Login and return the accessToken for the given role."""
    user = TEST_USERS[role]
    resp = requests.post(
        f"{{BASE_URL}}{{LOGIN_ENDPOINT}}",
        json={{"email": user["email"], "password": user["password"]}},
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json().get("accessToken", "")


@pytest.fixture(scope="session")
def base_url() -> str:
    return BASE_URL


@pytest.fixture(scope="session")
def requests_session():
    """Shared requests.Session for the entire test session."""
    session = requests.Session()
    yield session
    session.close()


@pytest.fixture(scope="session")
def auth_headers() -> dict:
    """Bearer token headers for the Super Admin role."""
    return {{"Authorization": f"Bearer {{_get_token('superadmin')}}"}}


@pytest.fixture(scope="session")
def merchant_headers() -> dict:
    """Bearer token headers for the Merchant role."""
    return {{"Authorization": f"Bearer {{_get_token('merchant')}}"}}


@pytest.fixture(scope="session")
def customer_headers() -> dict:
    """Bearer token headers for the Customer role."""
    return {{"Authorization": f"Bearer {{_get_token('customer')}}"}}
'''.format(base_url=base_url)

    os.makedirs(tests_dir, exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

    return path


def write_pytest_ini(marks: List[str], force: bool) -> str:
    path = "pytest.ini"

    mark_lines = "\n".join(f"    {m}: custom mark for {m} tests" for m in marks)

    if os.path.exists(path) and not force:
        with open(path, "r") as f:
            content = f.read()

        # Check if [pytest] header exists
        if "[pytest]" not in content:
            content = "[pytest]\n" + content
            
        # Ensure 'markers =' line exists
        if "markers =" not in content:
            content = content.replace("[pytest]", "[pytest]\nmarkers =")

        # Find marks that aren't registered yet
        missing = [m for m in marks if f"{m}:" not in content]
        
        if not missing:
            print("  [skip] pytest.ini already up to date")
            return path

        # Add missing marks under the markers section
        new_marks = "\n".join(f"    {m}: priority or category mark" for m in missing)
        content = content.replace("markers =", f"markers =\n{new_marks}")
        
        with open(path, "w") as f:
            f.write(content)
            
        print(f"  [update] pytest.ini — registered {len(missing)} marks: {', '.join(missing)}")
        return path

    # If force or file doesn't exist, create fresh
    content = f"[pytest]\nmarkers =\n{mark_lines}\n"
    with open(path, "w") as f:
        f.write(content)

    return path

# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate conftest.py and pytest.ini from OpenAPI spec.")
    parser.add_argument("--spec",      default="requirements/openapi.json", help="Path to openapi.json")
    parser.add_argument("--tests-dir", default="tests",             help="Path to tests directory")
    parser.add_argument("--force",     action="store_true",         help="Overwrite existing files")
    args = parser.parse_args()

    if not os.path.exists(args.spec):
        print("! Spec not found: " + args.spec)
        raise SystemExit(1)

    spec     = load_spec(args.spec)
    base_url = extract_base_url(spec)
    marks    = extract_marks(spec)

    print("  [spec]     " + args.spec)
    print("  [base_url] " + base_url)
    print("  [marks]    " + ", ".join(marks))

    conftest_path = write_conftest(args.tests_dir, base_url, args.force)
    ini_path      = write_pytest_ini(marks, args.force)

    print("  [ok] " + conftest_path)
    print("  [ok] " + ini_path)
    print("  Next: python3 scripts/generate_api_test_scripts.py ...")


if __name__ == "__main__":
    main()